import { Attribute, AttributeType } from "@prisma/client";

export const testAttributes: Attribute[] = [
  {
    id: "19asd239SD23ksd",
    supplierId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: "Rich Text Description",
    type: AttributeType.HTML,
    description: null,
    required: false,
    enrichmentInstructions: null,
    enrichmentEnabled: false,
    selectOptions: [],
    measureUnits: [],
  },
  {
    id: "sbsdg8sJSD23hs40",
    supplierId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: "Has Discount",
    type: AttributeType.BOOLEAN,
    description: null,
    required: false,
    enrichmentInstructions: null,
    enrichmentEnabled: false,
    selectOptions: [],
    measureUnits: [],
  },
  {
    id: "hgijdfg8s7SDnss",
    supplierId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: "Media",
    type: AttributeType.MEDIA,
    description: null,
    required: false,
    enrichmentInstructions: null,
    enrichmentEnabled: false,
    selectOptions: [],
    measureUnits: [],
  },
  {
    id: "Isdo48jhgA64jsfh",
    supplierId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: "Barcode",
    type: AttributeType.NUMBER,
    description: null,
    required: false,
    enrichmentInstructions: null,
    enrichmentEnabled: false,
    selectOptions: [],
    measureUnits: [],
  },
  {
    id: "98hlfgk23jsdIsd",
    supplierId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: "Brand",
    type: AttributeType.SHORT_TEXT,
    description: null,
    required: false,
    enrichmentInstructions: null,
    enrichmentEnabled: false,
    selectOptions: [],
    measureUnits: [],
  },
  {
    id: "PWsfgJFK37sd9we23",
    supplierId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    name: "Weight",
    type: AttributeType.MEASURE,
    description: null,
    required: false,
    enrichmentInstructions: null,
    enrichmentEnabled: false,
    selectOptions: [],
    measureUnits: ["KG", "G", "LBS"],
  },
];
